# Generated by Django 4.0.7 on 2024-09-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=35, null=True)),
                ('Customer_since', models.DateField(null=True)),
                ('Customer_location', models.CharField(max_length=50)),
            ],
        ),
    ]
