# Generated by Django 4.2.16 on 2024-09-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(null=True)),
                ('quantity', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('gst_number', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('customer_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.mycustomer')),
                ('product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.myproducts')),
            ],
        ),
    ]
