# Generated by Django 4.0.7 on 2024-09-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=35, null=True)),
                ('product_code', models.CharField(max_length=35, null=True)),
                ('product_price', models.FloatField(default=0)),
                ('product_gst', models.IntegerField(default=0)),
                ('food_product', models.BooleanField(default=0)),
            ],
        ),
    ]
